### ISSUE TITLE
Errore Rapporto riguardante la costante di Nepero

### ISSUE THREAD

**Issue by mvilucchio** [paolini/AnalisiUno#13]
Credo ci sia un errore nella sezione sulla costante di Nepero, a pagine 65 dell'ultima versione degli appunti. Nell'esercizio 3.57 dovrebbe essere a_n / n_{n+1} anzichè il reciproco.
Matteo VIlucchio

**Comment by paolini** [comment]
Sì, grazie della osservazione!

Se non le dispiace posso aggiungere il suo nome nell’elenco dei “contributi”. E’ uno studente di fisica, vero?

saluti,
E.

**Comment by mvilucchio** [comment]
Certo, mi farebbe molto piacere essere aggiunto tra i contributi, si sono uno studente del primo anno di Fisica.
Non per fare il pesante, ma volevo chiederle anche per un chiarimento sulla dimostrazione del Lemma "Ogni successione di Cauchy è limitata". Nel definire la costante maggiore di goni termine della serie lei riporta il massimo tra d(x_1. x_0) e d(x_0, x_1). Ma siccome per le proprietà di distanza sono ugiali non è ridondante?
Grazie per la comprensione
Matteo

**Comment by paolini** [comment]
Risolto con f541393cbdba9d6ce3118b72b7255dfe672e5d5e e baa96d8b21508e714c9cf18695c279566bf5a397
