### ISSUE TITLE
Definizione di intorno

### ISSUE THREAD

**Issue by tetrahedronix** [paolini/AnalisiUno#15]
La definizione di intorno data nel capitolo 5 può essere vista come una funzione I(x) che prende in ingresso un limite e restituisce un intorno?

**Comment by paolini** [comment]
Non direi... gli intori sono insiemi di punti e le famiglie di intorni sono insiemi di intorni (quindi insiemi di insiemi di punti)

** aggiunta **
comunque la famiglia di intorni dipende dal punto quindi formalmente è una funzione che prende in ingresso il punto (limite) e restituisce una famiglia di intorni.

**Comment by tetrahedronix** [comment]
Va bene, grazie.
