### ISSUE TITLE
Probabile refuso

### ISSUE THREAD

**Issue by tetrahedronix** [paolini/AnalisiUno#16]
A pagina 79 della versione 19 Settembre 2019, nella dimostrazione del Teorema della Radice viene riportata la radice quadrata della successione _an_. Il rigo successivo viene di nuovo utilizzata radice quadrata ma nelle diseguaglianze successive compare radice n-esima, come mai?

**Comment by paolini** [comment]
Sì, è un refuso, ora lo correggo!

Se non ti spiace metterei il tuo nome nei ringraziamenti (fammi sapere nome e cognome o come vuoi essere chiamato).

**Comment by tetrahedronix** [comment]
La ringrazio, il mio nome è Giulio Carlo.
Il suo libro è fatto molto bene è mi sta aiutando a prepare l'esame di Matematica del Continuo, Università degli Studi di Milano.
