### ISSUE TITLE
Errore di battitura

### ISSUE THREAD

**Issue by Lorenzo-Guglielmi** [paolini/AnalisiUno#17]
Buonasera,
Ieri ho provato in qualche modo a suggerire una modifica del testo per un errore di battitura, ma ho fatto un macello, mi ha aperto una fork (che non so cosa sia), spero di non aver combinato disastri
Alla riga 4242 del codice del capitolo 01 sui numeri reali
4241 Diremo che la funzione $f$ è
4242 \emph{inferiormente limitato}%
c'è scritto che la funzione è "inferiormente limitato", invece che "inferiormente limitata". Nel riquadro a fianco al testo invece è scritto bene.
Se questo metodo di segnalazione va bene, nel caso io trovi altri errori di questo tipo, glieli manderò in questa modalità.

Buona giornata e scusi il disturbo

**Comment by paolini** [comment]
Grazie della segnalazione, il metodo va bene! Ho corretto. Un "fork" è una copia del codice con eventuali modifiche indipendenti dall'originale.
