### ISSUE TITLE
Richiamo a equazione sbagliata

### ISSUE THREAD

**Issue by Lorenzo-Guglielmi** [paolini/AnalisiUno#19]
Buonasera professore,
credo ci sia un errore di battitura a pagina 255, teorema 5.12, quando dimostra la linearità della somma nell'integrale.
"e dunque se 𝑓 e 𝑔 sono integrabili anche 𝑓 + 𝑔 risulta integrabile e vale la (5.3)."
L'equazione in questione non mi pare sia la 5.3, e cliccandoci sopra in realtà si viene mandati all'equazione 5.9.

**Comment by paolini** [comment]
Grazie, ho corretto!

**Comment by Lorenzo-Guglielmi** [comment]
Buonasera,
Scrivo qua per non creare un nuovo thread.
A pagina 253, capitolo 5.3, esempio 5.9, mi pare ci sia un errore di battitura nella dimostrazione.
"Allora basta osservare che, per la densità dei **razionali,** in qualunque intervallino 𝐼 = [𝑥𝑘−1 , 𝑥𝑘 ] sono presenti infiniti punti razionali e infiniti punti irrazionali."
Viene menzionata la densità dei razionali, ma non quella degli irrazionali, per affermare che ci sono infiniti punti irrazionali in ogni intervallino. Credo volesse scrivere "densità dei reali".

**Comment by paolini** [comment]
Ho aggiunto la "densità degli irrazionali" come esercizio. E' conseguenza della densità dei razionali, basta osservare che i multipli razionali di radice di due (ad esempio) sono anch'essi densi. La densità dei reali invece non basterebbe.
