### ISSUE TITLE
Errore di battitura

### ISSUE THREAD

**Issue by Lorenzo-Guglielmi** [paolini/AnalisiUno#20]
Buongiorno professore,
A pagina 276, capitolo 5.8, c'è un errore di battitura:

"Per trovare i coefficienti 𝐴, 𝐵, 𝐶, . . . , 𝐻 (il numero dei coefficienti è pari al grado del polinomio
a denominatore) è sufficiente svolgere la derivata in (5.18) **[qui credo manchi una virgola]** mettere a denominatore
comune tutti gli addendi e **uguagliare con la funzione razionali originale**"

**Comment by paolini** [comment]
Ho corretto, grazie!
